### ISSUE TITLE
3D Shape Checklist

### ISSUE THREAD

**Issue by seveibar** [tscircuit/jscad-fiber#2]
### Cuboids
- [x] Cube
- [x] Cuboid
- [x] Rounded Cuboid

### Spheroids
- [x] Sphere (with custom segments)
- [x] Sphere (default)
- [x] Geodesic Sphere (low frequency)
- [x] Geodesic Sphere (high frequency)

### Ellipsoids
- [x] Ellipsoid

### Cylinders
- [x] Cylinder
- [x] Rounded Cylinder
- [x] Cylindrical Elliptic (cone)
- [x] Cylindrical Elliptic (twisted)
- [x] Cylindrical Elliptic (partial)

### Torii
- [x] Torus (default)
- [x] Torus (custom)
